name: upper-build
on: 
  push:
    paths:
      - ".github/workflows/upper-build.yml"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
        run: python --version
      - name: Update python version
        uses: actions/setup-python@v5
          with:
            python-version: '5.6.0'
        run: python --version
